// <auto-generated />
using System;
using AnimeSaveOneDropOne.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimeSaveOneDropOne.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210110204729_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("AnimeSaveOneDropOne.Shared.AnimeCharacter", b =>
                {
                    b.Property<int>("MalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AnimeMalId")
                        .HasColumnType("int");

                    b.Property<int?>("AnimeMeMalId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("PreviousRank")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("MalId");

                    b.HasIndex("AnimeMeMalId");

                    b.ToTable("AnimeCharacters");
                });

            modelBuilder.Entity("AnimeSaveOneDropOne.Shared.AnimeMe", b =>
                {
                    b.Property<int>("MalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MalId");

                    b.ToTable("Animes");
                });

            modelBuilder.Entity("AnimeSaveOneDropOne.Shared.AnimeCharacter", b =>
                {
                    b.HasOne("AnimeSaveOneDropOne.Shared.AnimeMe", null)
                        .WithMany("AnimeCharacters")
                        .HasForeignKey("AnimeMeMalId");
                });

            modelBuilder.Entity("AnimeSaveOneDropOne.Shared.AnimeMe", b =>
                {
                    b.Navigation("AnimeCharacters");
                });
#pragma warning restore 612, 618
        }
    }
}
