// <auto-generated />
using System;
using AnimeSaveOneDropOne.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimeSaveOneDropOne.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("AnimeSaveOneDropOne.Shared.AnimeCharacter", b =>
                {
                    b.Property<int>("MalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AnimeMalId")
                        .HasColumnType("int");

                    b.Property<int?>("AnimeMeMalId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("PreviousRank")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("MalId");

                    b.HasIndex("AnimeMeMalId");

                    b.ToTable("AnimeCharacters");

                    b.HasData(
                        new
                        {
                            MalId = 1,
                            AnimeMalId = 1,
                            ImageUrl = "https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/149470781/original/cf87ada92b21431ab6418eeae2aac47aa6502d56/draw-cool-anime-or-manga-style-characters-fan-art-or-oc.png",
                            Name = "AMN",
                            Points = 0,
                            PreviousRank = 2,
                            Rank = 1
                        },
                        new
                        {
                            MalId = 2,
                            AnimeMalId = 1,
                            ImageUrl = "https://cdn.myanimelist.net/images/characters/2/284121.jpg",
                            Name = "Naruto",
                            Points = 0,
                            PreviousRank = 2,
                            Rank = 2
                        });
                });

            modelBuilder.Entity("AnimeSaveOneDropOne.Shared.AnimeMe", b =>
                {
                    b.Property<int>("MalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MalId");

                    b.ToTable("Animes");

                    b.HasData(
                        new
                        {
                            MalId = 1,
                            Description = "best anime",
                            ImageUrl = "book",
                            Name = "NDL Universe",
                            Url = "ndl-universe"
                        },
                        new
                        {
                            MalId = 2,
                            Description = "dats my nindo",
                            ImageUrl = "leaf",
                            Name = "Naruto",
                            Url = "naruto"
                        });
                });

            modelBuilder.Entity("AnimeSaveOneDropOne.Shared.AnimeCharacter", b =>
                {
                    b.HasOne("AnimeSaveOneDropOne.Shared.AnimeMe", null)
                        .WithMany("AnimeCharacters")
                        .HasForeignKey("AnimeMeMalId");
                });

            modelBuilder.Entity("AnimeSaveOneDropOne.Shared.AnimeMe", b =>
                {
                    b.Navigation("AnimeCharacters");
                });
#pragma warning restore 612, 618
        }
    }
}
